// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		Double greater = 0.0;
		Double smaller = 0.0;

		while (N > 0){
			if (Math.random() > 0.5) greater = greater + 1;
			else smaller = smaller + 1;
			N = N - 1;
		}

		if (greater != 0.0 && smaller !=0.0){
			if (greater >= smaller) System.out.println("Ratio:     " + smaller / greater);
			else System.out.println("Ratio:     " + greater / smaller);
		}

		

	}
}
